name: The best continuous integration workflow
'on':
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Testing with Gradle
        run: ./gradlew test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the contents of the repo 
        uses: actions/checkout@master

      #- name: Copy file via ssh password
      #  uses: appleboy/scp-action@master
      #  env:
      #    HOST: ${{ secrets.HOST }}
      #    USERNAME: ${{ secrets.USERNAME }}
      #    PORT: ${{ secrets.PORT }}
      #    KEY: ${{ secrets.KEY }}
      #  with:
      #    source: "src/"
      #    target: "~/prod"
      #- name: Add IPv6 config
      #  run: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

      #- name: Enable IPv6
      #  run: sudo sysctl net.ipv6.conf.all.disable_ipv6=0

      #- name: Enable IPv6 default
      #  run: sudo sysctl net.ipv6.conf.default.disable_ipv6=0

      #- name: Enable IPv6 lo
      #  run: sudo sysctl net.ipv6.conf.lo.disable_ipv6=0

      #- name: Enable IPv6 eth0
      #  run: sudo sysctl net.ipv6.conf.eth0.disable_ipv6=0
      - name: Install Open VPN
        run: sudo apt-get install openvpn

      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: '.github/vpn/config.ovpn'
          SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
          TLS_KEY: ${{ secrets.TLS_KEY }}
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}

      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}

      - name: kill vpn
        if: always()
        run: sudo killall openvpn

        #- name: Run manually
        #  env:
        #      SSHKEY: ${{ secrets.KEY }}
        #  run: |
        #      ls
        #      echo $SSHKEY > ssh_key.pem
        #      scp -6 -i ssh_key.pem -P ${{ secrets.PORT }} -r $PWD ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/prod
        #      rm -f ssh_key.pem
