name: The best continuous integration workflow
'on':
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Testing with Gradle
        run: ./gradlew test

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Copy folder content recursively to remote
        uses: actions/checkout@master

      #- name: Copy file via ssh password
      #  uses: appleboy/scp-action@master
      #  env:
      #    HOST: ${{ secrets.HOST }}
      #    USERNAME: ${{ secrets.USERNAME }}
      #    PORT: ${{ secrets.PORT }}
      #    KEY: ${{ secrets.KEY }}
      #  with:
      #    source: "src/"
      #    target: "~/prod"
      - name: Add IPv6 config
        run: sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'

      - name: Enable IPv6
        run: sysctl net.ipv6.conf.all.disable_ipv6=0

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/prod
            sudo docker-compose down && sudo docker-compose up --build -d
